// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { SatelliteDB } from '../satellite-db'
import { SatelliteService } from '../satellite.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-satellite-sorting',
  templateUrl: './satellite-sorting.component.html',
  styleUrls: ['./satellite-sorting.component.css']
})
export class SatelliteSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Satellite instances that are in the association
  associatedSatellites = new Array<SatelliteDB>();

  constructor(
    private satelliteService: SatelliteService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of satellite instances
    public dialogRef: MatDialogRef<SatelliteSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getSatellites()
  }

  getSatellites(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let satellite of this.frontRepo.Satellites_array) {
          let ID = this.dialogData.ID
          let revPointerID = satellite[this.dialogData.ReversePointer as keyof SatelliteDB] as unknown as NullInt64
          let revPointerID_Index = satellite[this.dialogData.ReversePointer + "_Index" as keyof SatelliteDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedSatellites.push(satellite)
          }
        }

        // sort associated satellite according to order
        this.associatedSatellites.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedSatellites, event.previousIndex, event.currentIndex);

    // set the order of Satellite instances
    let index = 0

    for (let satellite of this.associatedSatellites) {
      let revPointerID_Index = satellite[this.dialogData.ReversePointer + "_Index" as keyof SatelliteDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedSatellites.forEach(
      satellite => {
        this.satelliteService.updateSatellite(satellite, this.dialogData.GONG__StackPath)
          .subscribe(satellite => {
            this.satelliteService.SatelliteServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
