// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { ScenarioDB } from '../scenario-db'
import { ScenarioService } from '../scenario.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-scenariostable',
  templateUrl: './scenarios-table.component.html',
  styleUrls: ['./scenarios-table.component.css'],
})
export class ScenariosTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of Scenario instances
  selection: SelectionModel<ScenarioDB>;
  initialSelection = new Array<ScenarioDB>();

  // the data source for the table
  scenarios: ScenarioDB[];
  matTableDataSource: MatTableDataSource<ScenarioDB>

  // front repo, that will be referenced by this.scenarios
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (scenarioDB: ScenarioDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return scenarioDB.Name;

        case 'Lat':
          return scenarioDB.Lat;

        case 'Lng':
          return scenarioDB.Lng;

        case 'ZoomLevel':
          return scenarioDB.ZoomLevel;

        case 'MessageVisualSpeed':
          return scenarioDB.MessageVisualSpeed;

        default:
          return ScenarioDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (scenarioDB: ScenarioDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the scenarioDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += scenarioDB.Name.toLowerCase()
      mergedContent += scenarioDB.Lat.toString()
      mergedContent += scenarioDB.Lng.toString()
      mergedContent += scenarioDB.ZoomLevel.toString()
      mergedContent += scenarioDB.MessageVisualSpeed.toString()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private scenarioService: ScenarioService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of scenario instances
    public dialogRef: MatDialogRef<ScenariosTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.scenarioService.ScenarioServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getScenarios()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Lat",
        "Lng",
        "ZoomLevel",
        "MessageVisualSpeed",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Lat",
        "Lng",
        "ZoomLevel",
        "MessageVisualSpeed",
      ]
      this.selection = new SelectionModel<ScenarioDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getScenarios()
    this.matTableDataSource = new MatTableDataSource(this.scenarios)
  }

  getScenarios(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.scenarios = this.frontRepo.Scenarios_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.scenarios.forEach(
            scenario => {
              let ID = this.dialogData.ID
              let revPointer = scenario[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(scenario)
              }
            }
          )
          this.selection = new SelectionModel<ScenarioDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let scenario = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(scenario)
            }
          }
          this.selection = new SelectionModel<ScenarioDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.scenarios
      }
    )
  }

  // newScenario initiate a new scenario
  // create a new Scenario objet
  newScenario() {
  }

  deleteScenario(scenarioID: number, scenario: ScenarioDB) {
    // list of scenarios is truncated of scenario before the delete
    this.scenarios = this.scenarios.filter(h => h !== scenario);

    this.scenarioService.deleteScenario(scenarioID).subscribe(
      scenario => {
        this.scenarioService.ScenarioServiceChanged.next("delete")
      }
    );
  }

  editScenario(scenarioID: number, scenario: ScenarioDB) {

  }

  // display scenario in router
  displayScenarioInRouter(scenarioID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongfly_go-" + "scenario-display", scenarioID])
  }

  // set editor outlet
  setEditorRouterOutlet(scenarioID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongfly_go_editor: ["github_com_fullstack_lang_gongfly_go-" + "scenario-detail", scenarioID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(scenarioID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongfly_go_presentation: ["github_com_fullstack_lang_gongfly_go-" + "scenario-presentation", scenarioID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.scenarios.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.scenarios.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<ScenarioDB>()

      // reset all initial selection of scenario that belong to scenario
      this.initialSelection.forEach(
        scenario => {
          scenario[this.dialogData.ReversePointer].Int64 = 0
          scenario[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(scenario)
        }
      )

      // from selection, set scenario that belong to scenario
      this.selection.selected.forEach(
        scenario => {
          let ID = +this.dialogData.ID
          scenario[this.dialogData.ReversePointer].Int64 = ID
          scenario[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(scenario)
        }
      )

      // update all scenario (only update selection & initial selection)
      toUpdate.forEach(
        scenario => {
          this.scenarioService.updateScenario(scenario)
            .subscribe(scenario => {
              this.scenarioService.ScenarioServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedScenario = new Set<number>()
      for (let scenario of this.initialSelection) {
        if (this.selection.selected.includes(scenario)) {
          // console.log("scenario " + scenario.Name + " is still selected")
        } else {
          console.log("scenario " + scenario.Name + " has been unselected")
          unselectedScenario.add(scenario.ID)
          console.log("is unselected " + unselectedScenario.has(scenario.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let scenario = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedScenario.has(scenario.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          scenario => {
            if (!this.initialSelection.includes(scenario)) {
              // console.log("scenario " + scenario.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + scenario.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = scenario.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("scenario " + scenario.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<ScenarioDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
