// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { SatelliteDB } from '../satellite-db'
import { SatelliteService } from '../satellite.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-satellitestable',
  templateUrl: './satellites-table.component.html',
  styleUrls: ['./satellites-table.component.css'],
})
export class SatellitesTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Satellite instances
  selection: SelectionModel<SatelliteDB> = new (SelectionModel)
  initialSelection = new Array<SatelliteDB>()

  // the data source for the table
  satellites: SatelliteDB[] = []
  matTableDataSource: MatTableDataSource<SatelliteDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.satellites
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (satelliteDB: SatelliteDB, property: string) => {
      switch (property) {
        case 'ID':
          return satelliteDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return satelliteDB.Name;

        case 'Line1':
          return satelliteDB.Line1;

        case 'Line2':
          return satelliteDB.Line2;

        case 'Lat':
          return satelliteDB.Lat;

        case 'Lng':
          return satelliteDB.Lng;

        case 'Heading':
          return satelliteDB.Heading;

        case 'Level':
          return satelliteDB.Level;

        case 'Speed':
          return satelliteDB.Speed;

        case 'VerticalSpeed':
          return satelliteDB.VerticalSpeed;

        case 'Timestampstring':
          return satelliteDB.Timestampstring;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (satelliteDB: SatelliteDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the satelliteDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += satelliteDB.Name.toLowerCase()
      mergedContent += satelliteDB.Line1.toLowerCase()
      mergedContent += satelliteDB.Line2.toLowerCase()
      mergedContent += satelliteDB.Lat.toString()
      mergedContent += satelliteDB.Lng.toString()
      mergedContent += satelliteDB.Heading.toString()
      mergedContent += satelliteDB.Level.toString()
      mergedContent += satelliteDB.Speed.toString()
      mergedContent += satelliteDB.VerticalSpeed.toString()
      mergedContent += satelliteDB.Timestampstring.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private satelliteService: SatelliteService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of satellite instances
    public dialogRef: MatDialogRef<SatellitesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.satelliteService.SatelliteServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getSatellites()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Line1",
        "Line2",
        "Lat",
        "Lng",
        "Heading",
        "Level",
        "Speed",
        "VerticalSpeed",
        "Timestampstring",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Line1",
        "Line2",
        "Lat",
        "Lng",
        "Heading",
        "Level",
        "Speed",
        "VerticalSpeed",
        "Timestampstring",
      ]
      this.selection = new SelectionModel<SatelliteDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getSatellites()
    this.matTableDataSource = new MatTableDataSource(this.satellites)
  }

  getSatellites(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.satellites = this.frontRepo.Satellites_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let satellite of this.satellites) {
            let ID = this.dialogData.ID
            let revPointer = satellite[this.dialogData.ReversePointer as keyof SatelliteDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(satellite)
            }
            this.selection = new SelectionModel<SatelliteDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, SatelliteDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as SatelliteDB[]
          for (let associationInstance of sourceField) {
            let satellite = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as SatelliteDB
            this.initialSelection.push(satellite)
          }

          this.selection = new SelectionModel<SatelliteDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.satellites
      }
    )
  }

  // newSatellite initiate a new satellite
  // create a new Satellite objet
  newSatellite() {
  }

  deleteSatellite(satelliteID: number, satellite: SatelliteDB) {
    // list of satellites is truncated of satellite before the delete
    this.satellites = this.satellites.filter(h => h !== satellite);

    this.satelliteService.deleteSatellite(satelliteID).subscribe(
      satellite => {
        this.satelliteService.SatelliteServiceChanged.next("delete")
      }
    );
  }

  editSatellite(satelliteID: number, satellite: SatelliteDB) {

  }

  // display satellite in router
  displaySatelliteInRouter(satelliteID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongfly_go-" + "satellite-display", satelliteID])
  }

  // set editor outlet
  setEditorRouterOutlet(satelliteID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongfly_go_editor: ["github_com_fullstack_lang_gongfly_go-" + "satellite-detail", satelliteID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(satelliteID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongfly_go_presentation: ["github_com_fullstack_lang_gongfly_go-" + "satellite-presentation", satelliteID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.satellites.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.satellites.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<SatelliteDB>()

      // reset all initial selection of satellite that belong to satellite
      for (let satellite of this.initialSelection) {
        let index = satellite[this.dialogData.ReversePointer as keyof SatelliteDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(satellite)

      }

      // from selection, set satellite that belong to satellite
      for (let satellite of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = satellite[this.dialogData.ReversePointer as keyof SatelliteDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(satellite)
      }


      // update all satellite (only update selection & initial selection)
      for (let satellite of toUpdate) {
        this.satelliteService.updateSatellite(satellite)
          .subscribe(satellite => {
            this.satelliteService.SatelliteServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, SatelliteDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedSatellite = new Set<number>()
      for (let satellite of this.initialSelection) {
        if (this.selection.selected.includes(satellite)) {
          // console.log("satellite " + satellite.Name + " is still selected")
        } else {
          console.log("satellite " + satellite.Name + " has been unselected")
          unselectedSatellite.add(satellite.ID)
          console.log("is unselected " + unselectedSatellite.has(satellite.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let satellite = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as SatelliteDB
      if (unselectedSatellite.has(satellite.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<SatelliteDB>) = new Array<SatelliteDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          satellite => {
            if (!this.initialSelection.includes(satellite)) {
              // console.log("satellite " + satellite.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + satellite.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = satellite.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = satellite.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("satellite " + satellite.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<SatelliteDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
