// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { OpsLineDB } from '../opsline-db'
import { OpsLineService } from '../opsline.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-opslinestable',
  templateUrl: './opslines-table.component.html',
  styleUrls: ['./opslines-table.component.css'],
})
export class OpsLinesTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of OpsLine instances
  selection: SelectionModel<OpsLineDB> = new (SelectionModel)
  initialSelection = new Array<OpsLineDB>()

  // the data source for the table
  opslines: OpsLineDB[] = []
  matTableDataSource: MatTableDataSource<OpsLineDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.opslines
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (opslineDB: OpsLineDB, property: string) => {
      switch (property) {
        case 'ID':
          return opslineDB.ID

        // insertion point for specific sorting accessor
        case 'IsTransmitting':
          return opslineDB.IsTransmitting?"true":"false";

        case 'TransmissionMessage':
          return opslineDB.TransmissionMessage;

        case 'IsTransmittingBackward':
          return opslineDB.IsTransmittingBackward?"true":"false";

        case 'TransmissionMessageBackward':
          return opslineDB.TransmissionMessageBackward;

        case 'Scenario':
          return (opslineDB.Scenario ? opslineDB.Scenario.Name : '');

        case 'State':
          return opslineDB.State;

        case 'Name':
          return opslineDB.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (opslineDB: OpsLineDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the opslineDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += opslineDB.TransmissionMessage.toLowerCase()
      mergedContent += opslineDB.TransmissionMessageBackward.toLowerCase()
      if (opslineDB.Scenario) {
        mergedContent += opslineDB.Scenario.Name.toLowerCase()
      }
      mergedContent += opslineDB.State.toLowerCase()
      mergedContent += opslineDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private opslineService: OpsLineService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of opsline instances
    public dialogRef: MatDialogRef<OpsLinesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.opslineService.OpsLineServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getOpsLines()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "IsTransmitting",
        "TransmissionMessage",
        "IsTransmittingBackward",
        "TransmissionMessageBackward",
        "Scenario",
        "State",
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "IsTransmitting",
        "TransmissionMessage",
        "IsTransmittingBackward",
        "TransmissionMessageBackward",
        "Scenario",
        "State",
        "Name",
      ]
      this.selection = new SelectionModel<OpsLineDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getOpsLines()
    this.matTableDataSource = new MatTableDataSource(this.opslines)
  }

  getOpsLines(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.opslines = this.frontRepo.OpsLines_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let opsline of this.opslines) {
            let ID = this.dialogData.ID
            let revPointer = opsline[this.dialogData.ReversePointer as keyof OpsLineDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(opsline)
            }
            this.selection = new SelectionModel<OpsLineDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, OpsLineDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as OpsLineDB[]
          for (let associationInstance of sourceField) {
            let opsline = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as OpsLineDB
            this.initialSelection.push(opsline)
          }

          this.selection = new SelectionModel<OpsLineDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.opslines
      }
    )
  }

  // newOpsLine initiate a new opsline
  // create a new OpsLine objet
  newOpsLine() {
  }

  deleteOpsLine(opslineID: number, opsline: OpsLineDB) {
    // list of opslines is truncated of opsline before the delete
    this.opslines = this.opslines.filter(h => h !== opsline);

    this.opslineService.deleteOpsLine(opslineID).subscribe(
      opsline => {
        this.opslineService.OpsLineServiceChanged.next("delete")
      }
    );
  }

  editOpsLine(opslineID: number, opsline: OpsLineDB) {

  }

  // display opsline in router
  displayOpsLineInRouter(opslineID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongfly_go-" + "opsline-display", opslineID])
  }

  // set editor outlet
  setEditorRouterOutlet(opslineID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongfly_go_editor: ["github_com_fullstack_lang_gongfly_go-" + "opsline-detail", opslineID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.opslines.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.opslines.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<OpsLineDB>()

      // reset all initial selection of opsline that belong to opsline
      for (let opsline of this.initialSelection) {
        let index = opsline[this.dialogData.ReversePointer as keyof OpsLineDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(opsline)

      }

      // from selection, set opsline that belong to opsline
      for (let opsline of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = opsline[this.dialogData.ReversePointer as keyof OpsLineDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(opsline)
      }


      // update all opsline (only update selection & initial selection)
      for (let opsline of toUpdate) {
        this.opslineService.updateOpsLine(opsline)
          .subscribe(opsline => {
            this.opslineService.OpsLineServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, OpsLineDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedOpsLine = new Set<number>()
      for (let opsline of this.initialSelection) {
        if (this.selection.selected.includes(opsline)) {
          // console.log("opsline " + opsline.Name + " is still selected")
        } else {
          console.log("opsline " + opsline.Name + " has been unselected")
          unselectedOpsLine.add(opsline.ID)
          console.log("is unselected " + unselectedOpsLine.has(opsline.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let opsline = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as OpsLineDB
      if (unselectedOpsLine.has(opsline.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<OpsLineDB>) = new Array<OpsLineDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          opsline => {
            if (!this.initialSelection.includes(opsline)) {
              // console.log("opsline " + opsline.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + opsline.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = opsline.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = opsline.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("opsline " + opsline.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<OpsLineDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
