// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { CenterConceptDB } from './centerconcept-db';

@Injectable({
  providedIn: 'root'
})
export class CenterConceptService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  CenterConceptServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private centerconceptsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
	let origin = this.document.location.origin
    
	// if debugging with ng, replace 4200 with 8080
	origin = origin.replace("4200", "8080")

    // compute path to the service
    this.centerconceptsUrl = origin + '/api/github.com/fullstack-lang/gongfly/go/v1/centerconcepts';
   }

  /** GET centerconcepts from the server */
  getCenterConcepts(): Observable<CenterConceptDB[]> {
    return this.http.get<CenterConceptDB[]>(this.centerconceptsUrl)
      .pipe(
        tap(_ => this.log('fetched centerconcepts')),
        catchError(this.handleError<CenterConceptDB[]>('getCenterConcepts', []))
      );
  }

  /** GET centerconcept by id. Will 404 if id not found */
  getCenterConcept(id: number): Observable<CenterConceptDB> {
    const url = `${this.centerconceptsUrl}/${id}`;
    return this.http.get<CenterConceptDB>(url).pipe(
      tap(_ => this.log(`fetched centerconcept id=${id}`)),
      catchError(this.handleError<CenterConceptDB>(`getCenterConcept id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new centerconcept to the server */
  postCenterConcept(centerconceptdb: CenterConceptDB): Observable<CenterConceptDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

		return this.http.post<CenterConceptDB>(this.centerconceptsUrl, centerconceptdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted centerconceptdb id=${centerconceptdb.ID}`)
			}),
			catchError(this.handleError<CenterConceptDB>('postCenterConcept'))
		);
  }

  /** DELETE: delete the centerconceptdb from the server */
  deleteCenterConcept(centerconceptdb: CenterConceptDB | number): Observable<CenterConceptDB> {
    const id = typeof centerconceptdb === 'number' ? centerconceptdb : centerconceptdb.ID;
    const url = `${this.centerconceptsUrl}/${id}`;

    return this.http.delete<CenterConceptDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted centerconceptdb id=${id}`)),
      catchError(this.handleError<CenterConceptDB>('deleteCenterConcept'))
    );
  }

  /** PUT: update the centerconceptdb on the server */
  updateCenterConcept(centerconceptdb: CenterConceptDB): Observable<CenterConceptDB> {
    const id = typeof centerconceptdb === 'number' ? centerconceptdb : centerconceptdb.ID;
    const url = `${this.centerconceptsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put(url, centerconceptdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated centerconceptdb id=${centerconceptdb.ID}`)
      }),
      catchError(this.handleError<CenterConceptDB>('updateCenterConcept'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
