// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { LinerDB } from './liner-db';

@Injectable({
  providedIn: 'root'
})
export class LinerService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  LinerServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private linersUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongfly/go/v1/liners';

  constructor(
    private http: HttpClient
  ) { }

  /** GET liners from the server */
  getLiners(): Observable<LinerDB[]> {
    return this.http.get<LinerDB[]>(this.linersUrl)
      .pipe(
        tap(_ => this.log('fetched liners')),
        catchError(this.handleError<LinerDB[]>('getLiners', []))
      );
  }

  /** GET liner by id. Will 404 if id not found */
  getLiner(id: number): Observable<LinerDB> {
    const url = `${this.linersUrl}/${id}`;
    return this.http.get<LinerDB>(url).pipe(
      tap(_ => this.log(`fetched liner id=${id}`)),
      catchError(this.handleError<LinerDB>(`getLiner id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new liner to the server */
  postLiner(linerdb: LinerDB): Observable<LinerDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    linerdb.ReporingLine = {}

		return this.http.post<LinerDB>(this.linersUrl, linerdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted linerdb id=${linerdb.ID}`)
			}),
			catchError(this.handleError<LinerDB>('postLiner'))
		);
  }

  /** DELETE: delete the linerdb from the server */
  deleteLiner(linerdb: LinerDB | number): Observable<LinerDB> {
    const id = typeof linerdb === 'number' ? linerdb : linerdb.ID;
    const url = `${this.linersUrl}/${id}`;

    return this.http.delete<LinerDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted linerdb id=${id}`)),
      catchError(this.handleError<LinerDB>('deleteLiner'))
    );
  }

  /** PUT: update the linerdb on the server */
  updateLiner(linerdb: LinerDB): Observable<LinerDB> {
    const id = typeof linerdb === 'number' ? linerdb : linerdb.ID;
    const url = `${this.linersUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    linerdb.ReporingLine = {}

    return this.http.put(url, linerdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated linerdb id=${linerdb.ID}`)
      }),
      catchError(this.handleError<LinerDB>('updateLiner'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
