// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { OpsLineDB } from './opsline-db';
import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { ScenarioDB } from './scenario-db'

@Injectable({
  providedIn: 'root'
})
export class OpsLineService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  OpsLineServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private opslinesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.opslinesUrl = origin + '/api/github.com/fullstack-lang/gongfly/go/v1/opslines';
  }

  /** GET opslines from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<OpsLineDB[]> {
    return this.getOpsLines(GONG__StackPath, frontRepo)
  }
  getOpsLines(GONG__StackPath: string, frontRepo: FrontRepo): Observable<OpsLineDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<OpsLineDB[]>(this.opslinesUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<OpsLineDB[]>('getOpsLines', []))
      );
  }

  /** GET opsline by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<OpsLineDB> {
    return this.getOpsLine(id, GONG__StackPath, frontRepo)
  }
  getOpsLine(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<OpsLineDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.opslinesUrl}/${id}`;
    return this.http.get<OpsLineDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched opsline id=${id}`)),
      catchError(this.handleError<OpsLineDB>(`getOpsLine id=${id}`))
    );
  }

  /** POST: add a new opsline to the server */
  post(opslinedb: OpsLineDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<OpsLineDB> {
    return this.postOpsLine(opslinedb, GONG__StackPath, frontRepo)
  }
  postOpsLine(opslinedb: OpsLineDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<OpsLineDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    if (opslinedb.Scenario != undefined) {
      opslinedb.OpsLinePointersEncoding.ScenarioID.Int64 = opslinedb.Scenario.ID
      opslinedb.OpsLinePointersEncoding.ScenarioID.Valid = true
    }
    opslinedb.Scenario = undefined

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<OpsLineDB>(this.opslinesUrl, opslinedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        opslinedb.Scenario = frontRepo.Scenarios.get(opslinedb.OpsLinePointersEncoding.ScenarioID.Int64)
        // this.log(`posted opslinedb id=${opslinedb.ID}`)
      }),
      catchError(this.handleError<OpsLineDB>('postOpsLine'))
    );
  }

  /** DELETE: delete the opslinedb from the server */
  delete(opslinedb: OpsLineDB | number, GONG__StackPath: string): Observable<OpsLineDB> {
    return this.deleteOpsLine(opslinedb, GONG__StackPath)
  }
  deleteOpsLine(opslinedb: OpsLineDB | number, GONG__StackPath: string): Observable<OpsLineDB> {
    const id = typeof opslinedb === 'number' ? opslinedb : opslinedb.ID;
    const url = `${this.opslinesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<OpsLineDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted opslinedb id=${id}`)),
      catchError(this.handleError<OpsLineDB>('deleteOpsLine'))
    );
  }

  /** PUT: update the opslinedb on the server */
  update(opslinedb: OpsLineDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<OpsLineDB> {
    return this.updateOpsLine(opslinedb, GONG__StackPath, frontRepo)
  }
  updateOpsLine(opslinedb: OpsLineDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<OpsLineDB> {
    const id = typeof opslinedb === 'number' ? opslinedb : opslinedb.ID;
    const url = `${this.opslinesUrl}/${id}`;

    // insertion point for reset of pointers (to avoid circular JSON)
    // and encoding of pointers
    if (opslinedb.Scenario != undefined) {
      opslinedb.OpsLinePointersEncoding.ScenarioID.Int64 = opslinedb.Scenario.ID
      opslinedb.OpsLinePointersEncoding.ScenarioID.Valid = true
    }
    opslinedb.Scenario = undefined

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<OpsLineDB>(url, opslinedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        opslinedb.Scenario = frontRepo.Scenarios.get(opslinedb.OpsLinePointersEncoding.ScenarioID.Int64)
        // this.log(`updated opslinedb id=${opslinedb.ID}`)
      }),
      catchError(this.handleError<OpsLineDB>('updateOpsLine'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in OpsLineService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("OpsLineService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
