// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { OpsLineAPI } from './opsline-api';
import { OpsLineDB } from './opsline-db';

@Injectable({
  providedIn: 'root'
})
export class OpsLineService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  OpsLineServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private opslinesUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongfly/go/v1/opslines';

  constructor(
    private http: HttpClient
  ) { }

  /** GET opslines from the server */
  getOpsLines(): Observable<OpsLineDB[]> {
    return this.http.get<OpsLineDB[]>(this.opslinesUrl)
      .pipe(
        tap(_ => this.log('fetched opslines')),
        catchError(this.handleError<OpsLineDB[]>('getOpsLines', []))
      );
  }

  /** GET opsline by id. Will 404 if id not found */
  getOpsLine(id: number): Observable<OpsLineDB> {
    const url = `${this.opslinesUrl}/${id}`;
    return this.http.get<OpsLineDB>(url).pipe(
      tap(_ => this.log(`fetched opsline id=${id}`)),
      catchError(this.handleError<OpsLineDB>(`getOpsLine id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new opsline to the server */
  postOpsLine(opslinedb: OpsLineDB): Observable<OpsLineDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    opslinedb.Scenario = {}

		return this.http.post<OpsLineDB>(this.opslinesUrl, opslinedb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted opslinedb id=${opslinedb.ID}`)
			}),
			catchError(this.handleError<OpsLineDB>('postOpsLine'))
		);
  }

  /** DELETE: delete the opslinedb from the server */
  deleteOpsLine(opslinedb: OpsLineDB | number): Observable<OpsLineDB> {
    const id = typeof opslinedb === 'number' ? opslinedb : opslinedb.ID;
    const url = `${this.opslinesUrl}/${id}`;

    return this.http.delete<OpsLineDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted opslinedb id=${id}`)),
      catchError(this.handleError<OpsLineDB>('deleteOpsLine'))
    );
  }

  /** PUT: update the opslinedb on the server */
  updateOpsLine(opslinedb: OpsLineDB): Observable<OpsLineDB> {
    const id = typeof opslinedb === 'number' ? opslinedb : opslinedb.ID;
    const url = `${this.opslinesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    opslinedb.Scenario = {}

    return this.http.put(url, opslinedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated opslinedb id=${opslinedb.ID}`)
      }),
      catchError(this.handleError<OpsLineDB>('updateOpsLine'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
