// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { OrderDB } from './order-db';

@Injectable({
  providedIn: 'root'
})
export class OrderService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  OrderServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private ordersUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
	let origin = this.document.location.origin
    
	// if debugging with ng, replace 4200 with 8080
	origin = origin.replace("4200", "8080")

    // compute path to the service
    this.ordersUrl = origin + '/api/github.com/fullstack-lang/gongfly/go/v1/orders';
   }

  /** GET orders from the server */
  getOrders(): Observable<OrderDB[]> {
    return this.http.get<OrderDB[]>(this.ordersUrl)
      .pipe(
        tap(_ => this.log('fetched orders')),
        catchError(this.handleError<OrderDB[]>('getOrders', []))
      );
  }

  /** GET order by id. Will 404 if id not found */
  getOrder(id: number): Observable<OrderDB> {
    const url = `${this.ordersUrl}/${id}`;
    return this.http.get<OrderDB>(url).pipe(
      tap(_ => this.log(`fetched order id=${id}`)),
      catchError(this.handleError<OrderDB>(`getOrder id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new order to the server */
  postOrder(orderdb: OrderDB): Observable<OrderDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    orderdb.Target = {}

		return this.http.post<OrderDB>(this.ordersUrl, orderdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted orderdb id=${orderdb.ID}`)
			}),
			catchError(this.handleError<OrderDB>('postOrder'))
		);
  }

  /** DELETE: delete the orderdb from the server */
  deleteOrder(orderdb: OrderDB | number): Observable<OrderDB> {
    const id = typeof orderdb === 'number' ? orderdb : orderdb.ID;
    const url = `${this.ordersUrl}/${id}`;

    return this.http.delete<OrderDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted orderdb id=${id}`)),
      catchError(this.handleError<OrderDB>('deleteOrder'))
    );
  }

  /** PUT: update the orderdb on the server */
  updateOrder(orderdb: OrderDB): Observable<OrderDB> {
    const id = typeof orderdb === 'number' ? orderdb : orderdb.ID;
    const url = `${this.ordersUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    orderdb.Target = {}

    return this.http.put(url, orderdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated orderdb id=${orderdb.ID}`)
      }),
      catchError(this.handleError<OrderDB>('updateOrder'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
