// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ReportDB } from './report-db';

@Injectable({
  providedIn: 'root'
})
export class ReportService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ReportServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private reportsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
	let origin = this.document.location.origin
    
	// if debugging with ng, replace 4200 with 8080
	origin = origin.replace("4200", "8080")

    // compute path to the service
    this.reportsUrl = origin + '/api/github.com/fullstack-lang/gongfly/go/v1/reports';
   }

  /** GET reports from the server */
  getReports(): Observable<ReportDB[]> {
    return this.http.get<ReportDB[]>(this.reportsUrl)
      .pipe(
        tap(_ => this.log('fetched reports')),
        catchError(this.handleError<ReportDB[]>('getReports', []))
      );
  }

  /** GET report by id. Will 404 if id not found */
  getReport(id: number): Observable<ReportDB> {
    const url = `${this.reportsUrl}/${id}`;
    return this.http.get<ReportDB>(url).pipe(
      tap(_ => this.log(`fetched report id=${id}`)),
      catchError(this.handleError<ReportDB>(`getReport id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new report to the server */
  postReport(reportdb: ReportDB): Observable<ReportDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    reportdb.About = {}
    reportdb.OpsLine = {}

		return this.http.post<ReportDB>(this.reportsUrl, reportdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted reportdb id=${reportdb.ID}`)
			}),
			catchError(this.handleError<ReportDB>('postReport'))
		);
  }

  /** DELETE: delete the reportdb from the server */
  deleteReport(reportdb: ReportDB | number): Observable<ReportDB> {
    const id = typeof reportdb === 'number' ? reportdb : reportdb.ID;
    const url = `${this.reportsUrl}/${id}`;

    return this.http.delete<ReportDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted reportdb id=${id}`)),
      catchError(this.handleError<ReportDB>('deleteReport'))
    );
  }

  /** PUT: update the reportdb on the server */
  updateReport(reportdb: ReportDB): Observable<ReportDB> {
    const id = typeof reportdb === 'number' ? reportdb : reportdb.ID;
    const url = `${this.reportsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    reportdb.About = {}
    reportdb.OpsLine = {}

    return this.http.put(url, reportdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated reportdb id=${reportdb.ID}`)
      }),
      catchError(this.handleError<ReportDB>('updateReport'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
