// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ScenarioDB } from './scenario-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class ScenarioService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ScenarioServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private scenariosUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.scenariosUrl = origin + '/api/github.com/fullstack-lang/gongfly/go/v1/scenarios';
  }

  /** GET scenarios from the server */
  getScenarios(GONG__StackPath: string): Observable<ScenarioDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<ScenarioDB[]>(this.scenariosUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched scenarios')),
        catchError(this.handleError<ScenarioDB[]>('getScenarios', []))
      );
  }

  /** GET scenario by id. Will 404 if id not found */
  getScenario(id: number, GONG__StackPath: string): Observable<ScenarioDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.scenariosUrl}/${id}`;
    return this.http.get<ScenarioDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched scenario id=${id}`)),
      catchError(this.handleError<ScenarioDB>(`getScenario id=${id}`))
    );
  }

  /** POST: add a new scenario to the server */
  postScenario(scenariodb: ScenarioDB, GONG__StackPath: string): Observable<ScenarioDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ScenarioDB>(this.scenariosUrl, scenariodb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted scenariodb id=${scenariodb.ID}`)
      }),
      catchError(this.handleError<ScenarioDB>('postScenario'))
    );
  }

  /** DELETE: delete the scenariodb from the server */
  deleteScenario(scenariodb: ScenarioDB | number, GONG__StackPath: string): Observable<ScenarioDB> {
    const id = typeof scenariodb === 'number' ? scenariodb : scenariodb.ID;
    const url = `${this.scenariosUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ScenarioDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted scenariodb id=${id}`)),
      catchError(this.handleError<ScenarioDB>('deleteScenario'))
    );
  }

  /** PUT: update the scenariodb on the server */
  updateScenario(scenariodb: ScenarioDB, GONG__StackPath: string): Observable<ScenarioDB> {
    const id = typeof scenariodb === 'number' ? scenariodb : scenariodb.ID;
    const url = `${this.scenariosUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ScenarioDB>(url, scenariodb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated scenariodb id=${scenariodb.ID}`)
      }),
      catchError(this.handleError<ScenarioDB>('updateScenario'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ScenarioService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("ScenarioService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
