// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ScenarioAPI } from './scenario-api';
import { ScenarioDB } from './scenario-db';

@Injectable({
  providedIn: 'root'
})
export class ScenarioService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ScenarioServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private scenariosUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongfly/go/v1/scenarios';

  constructor(
    private http: HttpClient
  ) { }

  /** GET scenarios from the server */
  getScenarios(): Observable<ScenarioDB[]> {
    return this.http.get<ScenarioDB[]>(this.scenariosUrl)
      .pipe(
        tap(_ => this.log('fetched scenarios')),
        catchError(this.handleError<ScenarioDB[]>('getScenarios', []))
      );
  }

  /** GET scenario by id. Will 404 if id not found */
  getScenario(id: number): Observable<ScenarioDB> {
    const url = `${this.scenariosUrl}/${id}`;
    return this.http.get<ScenarioDB>(url).pipe(
      tap(_ => this.log(`fetched scenario id=${id}`)),
      catchError(this.handleError<ScenarioDB>(`getScenario id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new scenario to the server */
  postScenario(scenariodb: ScenarioDB): Observable<ScenarioDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

		return this.http.post<ScenarioDB>(this.scenariosUrl, scenariodb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted scenariodb id=${scenariodb.ID}`)
			}),
			catchError(this.handleError<ScenarioDB>('postScenario'))
		);
  }

  /** DELETE: delete the scenariodb from the server */
  deleteScenario(scenariodb: ScenarioDB | number): Observable<ScenarioDB> {
    const id = typeof scenariodb === 'number' ? scenariodb : scenariodb.ID;
    const url = `${this.scenariosUrl}/${id}`;

    return this.http.delete<ScenarioDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted scenariodb id=${id}`)),
      catchError(this.handleError<ScenarioDB>('deleteScenario'))
    );
  }

  /** PUT: update the scenariodb on the server */
  updateScenario(scenariodb: ScenarioDB): Observable<ScenarioDB> {
    const id = typeof scenariodb === 'number' ? scenariodb : scenariodb.ID;
    const url = `${this.scenariosUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put(url, scenariodb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated scenariodb id=${scenariodb.ID}`)
      }),
      catchError(this.handleError<ScenarioDB>('updateScenario'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
