// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { SystemDB } from './system-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class SystemService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  SystemServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private systemsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.systemsUrl = origin + '/api/github.com/fullstack-lang/gongfly/go/v1/systems';
  }

  /** GET systems from the server */
  getSystems(): Observable<SystemDB[]> {
    return this.http.get<SystemDB[]>(this.systemsUrl)
      .pipe(
        tap(_ => this.log('fetched systems')),
        catchError(this.handleError<SystemDB[]>('getSystems', []))
      );
  }

  /** GET system by id. Will 404 if id not found */
  getSystem(id: number): Observable<SystemDB> {
    const url = `${this.systemsUrl}/${id}`;
    return this.http.get<SystemDB>(url).pipe(
      tap(_ => this.log(`fetched system id=${id}`)),
      catchError(this.handleError<SystemDB>(`getSystem id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new system to the server */
  postSystem(systemdb: SystemDB): Observable<SystemDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<SystemDB>(this.systemsUrl, systemdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted systemdb id=${systemdb.ID}`)
      }),
      catchError(this.handleError<SystemDB>('postSystem'))
    );
  }

  /** DELETE: delete the systemdb from the server */
  deleteSystem(systemdb: SystemDB | number): Observable<SystemDB> {
    const id = typeof systemdb === 'number' ? systemdb : systemdb.ID;
    const url = `${this.systemsUrl}/${id}`;

    return this.http.delete<SystemDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted systemdb id=${id}`)),
      catchError(this.handleError<SystemDB>('deleteSystem'))
    );
  }

  /** PUT: update the systemdb on the server */
  updateSystem(systemdb: SystemDB): Observable<SystemDB> {
    const id = typeof systemdb === 'number' ? systemdb : systemdb.ID;
    const url = `${this.systemsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<SystemDB>(url, systemdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated systemdb id=${systemdb.ID}`)
      }),
      catchError(this.handleError<SystemDB>('updateSystem'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
