// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { RadarDB } from '../radar-db'
import { RadarService } from '../radar.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-radar-sorting',
  templateUrl: './radar-sorting.component.html',
  styleUrls: ['./radar-sorting.component.css']
})
export class RadarSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of Radar instances that are in the association
  associatedRadars = new Array<RadarDB>();

  constructor(
    private radarService: RadarService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of radar instances
    public dialogRef: MatDialogRef<RadarSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getRadars()
  }

  getRadars(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let radar of this.frontRepo.Radars_array) {
          let ID = this.dialogData.ID
          let revPointerID = radar[this.dialogData.ReversePointer]
          let revPointerID_Index = radar[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedRadars.push(radar)
          }
        }

        // sort associated radar according to order
        this.associatedRadars.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedRadars, event.previousIndex, event.currentIndex);

    // set the order of Radar instances
    let index = 0
    
    for (let radar of this.associatedRadars) {
      let revPointerID_Index = radar[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedRadars.forEach(
      radar => {
        this.radarService.updateRadar(radar)
          .subscribe(radar => {
            this.radarService.RadarServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
