// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gongfly/go/models"
	"github.com/fullstack-lang/gongfly/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __CivilianAirport__dummysDeclaration__ models.CivilianAirport
var __CivilianAirport_time__dummyDeclaration time.Duration

// An CivilianAirportID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getCivilianAirport updateCivilianAirport deleteCivilianAirport
type CivilianAirportID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// CivilianAirportInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postCivilianAirport updateCivilianAirport
type CivilianAirportInput struct {
	// The CivilianAirport to submit or modify
	// in: body
	CivilianAirport *orm.CivilianAirportAPI
}

// GetCivilianAirports
//
// swagger:route GET /civilianairports civilianairports getCivilianAirports
//
// # Get all civilianairports
//
// Responses:
// default: genericError
//
//	200: civilianairportDBResponse
func GetCivilianAirports(c *gin.Context) {
	db := orm.BackRepo.BackRepoCivilianAirport.GetDB()

	// source slice
	var civilianairportDBs []orm.CivilianAirportDB

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GONG__StackPath", stackParam)
		}
	}

	query := db.Find(&civilianairportDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	civilianairportAPIs := make([]orm.CivilianAirportAPI, 0)

	// for each civilianairport, update fields from the database nullable fields
	for idx := range civilianairportDBs {
		civilianairportDB := &civilianairportDBs[idx]
		_ = civilianairportDB
		var civilianairportAPI orm.CivilianAirportAPI

		// insertion point for updating fields
		civilianairportAPI.ID = civilianairportDB.ID
		civilianairportDB.CopyBasicFieldsToCivilianAirport(&civilianairportAPI.CivilianAirport)
		civilianairportAPI.CivilianAirportPointersEnconding = civilianairportDB.CivilianAirportPointersEnconding
		civilianairportAPIs = append(civilianairportAPIs, civilianairportAPI)
	}

	c.JSON(http.StatusOK, civilianairportAPIs)
}

// PostCivilianAirport
//
// swagger:route POST /civilianairports civilianairports postCivilianAirport
//
// Creates a civilianairport
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostCivilianAirport(c *gin.Context) {

	// Validate input
	var input orm.CivilianAirportAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create civilianairport
	civilianairportDB := orm.CivilianAirportDB{}
	civilianairportDB.CivilianAirportPointersEnconding = input.CivilianAirportPointersEnconding
	civilianairportDB.CopyBasicFieldsFromCivilianAirport(&input.CivilianAirport)

	db := orm.BackRepo.BackRepoCivilianAirport.GetDB()
	query := db.Create(&civilianairportDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoCivilianAirport.CheckoutPhaseOneInstance(&civilianairportDB)
	civilianairport := (*orm.BackRepo.BackRepoCivilianAirport.Map_CivilianAirportDBID_CivilianAirportPtr)[civilianairportDB.ID]

	if civilianairport != nil {
		models.AfterCreateFromFront(&models.Stage, civilianairport)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, civilianairportDB)
}

// GetCivilianAirport
//
// swagger:route GET /civilianairports/{ID} civilianairports getCivilianAirport
//
// Gets the details for a civilianairport.
//
// Responses:
// default: genericError
//
//	200: civilianairportDBResponse
func GetCivilianAirport(c *gin.Context) {

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["stack"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GET params", stackParam)
		}
	}

	db := orm.BackRepo.BackRepoCivilianAirport.GetDB()

	// Get civilianairportDB in DB
	var civilianairportDB orm.CivilianAirportDB
	if err := db.First(&civilianairportDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var civilianairportAPI orm.CivilianAirportAPI
	civilianairportAPI.ID = civilianairportDB.ID
	civilianairportAPI.CivilianAirportPointersEnconding = civilianairportDB.CivilianAirportPointersEnconding
	civilianairportDB.CopyBasicFieldsToCivilianAirport(&civilianairportAPI.CivilianAirport)

	c.JSON(http.StatusOK, civilianairportAPI)
}

// UpdateCivilianAirport
//
// swagger:route PATCH /civilianairports/{ID} civilianairports updateCivilianAirport
//
// # Update a civilianairport
//
// Responses:
// default: genericError
//
//	200: civilianairportDBResponse
func UpdateCivilianAirport(c *gin.Context) {

	// Validate input
	var input orm.CivilianAirportAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	db := orm.BackRepo.BackRepoCivilianAirport.GetDB()

	// Get model if exist
	var civilianairportDB orm.CivilianAirportDB

	// fetch the civilianairport
	query := db.First(&civilianairportDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// update
	civilianairportDB.CopyBasicFieldsFromCivilianAirport(&input.CivilianAirport)
	civilianairportDB.CivilianAirportPointersEnconding = input.CivilianAirportPointersEnconding

	query = db.Model(&civilianairportDB).Updates(civilianairportDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	civilianairportNew := new(models.CivilianAirport)
	civilianairportDB.CopyBasicFieldsToCivilianAirport(civilianairportNew)

	// get stage instance from DB instance, and call callback function
	civilianairportOld := (*orm.BackRepo.BackRepoCivilianAirport.Map_CivilianAirportDBID_CivilianAirportPtr)[civilianairportDB.ID]
	if civilianairportOld != nil {
		models.AfterUpdateFromFront(&models.Stage, civilianairportOld, civilianairportNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the civilianairportDB
	c.JSON(http.StatusOK, civilianairportDB)
}

// DeleteCivilianAirport
//
// swagger:route DELETE /civilianairports/{ID} civilianairports deleteCivilianAirport
//
// # Delete a civilianairport
//
// default: genericError
//
//	200: civilianairportDBResponse
func DeleteCivilianAirport(c *gin.Context) {
	db := orm.BackRepo.BackRepoCivilianAirport.GetDB()

	// Get model if exist
	var civilianairportDB orm.CivilianAirportDB
	if err := db.First(&civilianairportDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&civilianairportDB)

	// get an instance (not staged) from DB instance, and call callback function
	civilianairportDeleted := new(models.CivilianAirport)
	civilianairportDB.CopyBasicFieldsToCivilianAirport(civilianairportDeleted)

	// get stage instance from DB instance, and call callback function
	civilianairportStaged := (*orm.BackRepo.BackRepoCivilianAirport.Map_CivilianAirportDBID_CivilianAirportPtr)[civilianairportDB.ID]
	if civilianairportStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, civilianairportStaged, civilianairportDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
