// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"net/http"
	"time"

	"github.com/fullstack-lang/gongfly/go/models"
	"github.com/fullstack-lang/gongfly/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __Liner__dummysDeclaration__ models.Liner
var __Liner_time__dummyDeclaration time.Duration

// An LinerID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getLiner updateLiner deleteLiner
type LinerID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// LinerInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postLiner updateLiner
type LinerInput struct {
	// The Liner to submit or modify
	// in: body
	Liner *orm.LinerAPI
}

// GetLiners
//
// swagger:route GET /liners liners getLiners
//
// Get all liners
//
// Responses:
//    default: genericError
//        200: linerDBsResponse
func GetLiners(c *gin.Context) {
	db := orm.BackRepo.BackRepoLiner.GetDB()
	
	// source slice
	var linerDBs []orm.LinerDB
	query := db.Find(&linerDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	linerAPIs := make([]orm.LinerAPI, 0)

	// for each liner, update fields from the database nullable fields
	for idx := range linerDBs {
		linerDB := &linerDBs[idx]
		_ = linerDB
		var linerAPI orm.LinerAPI

		// insertion point for updating fields
		linerAPI.ID = linerDB.ID
		linerDB.CopyBasicFieldsToLiner(&linerAPI.Liner)
		linerAPI.LinerPointersEnconding = linerDB.LinerPointersEnconding
		linerAPIs = append(linerAPIs, linerAPI)
	}

	c.JSON(http.StatusOK, linerAPIs)
}

// PostLiner
//
// swagger:route POST /liners liners postLiner
//
// Creates a liner
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Responses:
//       200: linerDBResponse
func PostLiner(c *gin.Context) {
	db := orm.BackRepo.BackRepoLiner.GetDB()

	// Validate input
	var input orm.LinerAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create liner
	linerDB := orm.LinerDB{}
	linerDB.LinerPointersEnconding = input.LinerPointersEnconding
	linerDB.CopyBasicFieldsFromLiner(&input.Liner)

	query := db.Create(&linerDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, linerDB)
}

// GetLiner
//
// swagger:route GET /liners/{ID} liners getLiner
//
// Gets the details for a liner.
//
// Responses:
//    default: genericError
//        200: linerDBResponse
func GetLiner(c *gin.Context) {
	db := orm.BackRepo.BackRepoLiner.GetDB()

	// Get linerDB in DB
	var linerDB orm.LinerDB
	if err := db.First(&linerDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var linerAPI orm.LinerAPI
	linerAPI.ID = linerDB.ID
	linerAPI.LinerPointersEnconding = linerDB.LinerPointersEnconding
	linerDB.CopyBasicFieldsToLiner(&linerAPI.Liner)

	c.JSON(http.StatusOK, linerAPI)
}

// UpdateLiner
//
// swagger:route PATCH /liners/{ID} liners updateLiner
//
// Update a liner
//
// Responses:
//    default: genericError
//        200: linerDBResponse
func UpdateLiner(c *gin.Context) {
	db := orm.BackRepo.BackRepoLiner.GetDB()

	// Get model if exist
	var linerDB orm.LinerDB

	// fetch the liner
	query := db.First(&linerDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.LinerAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	linerDB.CopyBasicFieldsFromLiner(&input.Liner)
	linerDB.LinerPointersEnconding = input.LinerPointersEnconding

	query = db.Model(&linerDB).Updates(linerDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the linerDB
	c.JSON(http.StatusOK, linerDB)
}

// DeleteLiner
//
// swagger:route DELETE /liners/{ID} liners deleteLiner
//
// Delete a liner
//
// Responses:
//    default: genericError
func DeleteLiner(c *gin.Context) {
	db := orm.BackRepo.BackRepoLiner.GetDB()

	// Get model if exist
	var linerDB orm.LinerDB
	if err := db.First(&linerDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&linerDB)

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
