// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gongfly/go/models"
	"github.com/fullstack-lang/gongfly/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __Message__dummysDeclaration__ models.Message
var __Message_time__dummyDeclaration time.Duration

// An MessageID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getMessage updateMessage deleteMessage
type MessageID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// MessageInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postMessage updateMessage
type MessageInput struct {
	// The Message to submit or modify
	// in: body
	Message *orm.MessageAPI
}

// GetMessages
//
// swagger:route GET /messages messages getMessages
//
// Get all messages
//
// Responses:
//    default: genericError
//        200: messageDBsResponse
func GetMessages(c *gin.Context) {
	db := orm.BackRepo.BackRepoMessage.GetDB()

	// source slice
	var messageDBs []orm.MessageDB
	query := db.Find(&messageDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	messageAPIs := make([]orm.MessageAPI, 0)

	// for each message, update fields from the database nullable fields
	for idx := range messageDBs {
		messageDB := &messageDBs[idx]
		_ = messageDB
		var messageAPI orm.MessageAPI

		// insertion point for updating fields
		messageAPI.ID = messageDB.ID
		messageDB.CopyBasicFieldsToMessage(&messageAPI.Message)
		messageAPI.MessagePointersEnconding = messageDB.MessagePointersEnconding
		messageAPIs = append(messageAPIs, messageAPI)
	}

	c.JSON(http.StatusOK, messageAPIs)
}

// PostMessage
//
// swagger:route POST /messages messages postMessage
//
// Creates a message
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Responses:
//       200: messageDBResponse
func PostMessage(c *gin.Context) {
	db := orm.BackRepo.BackRepoMessage.GetDB()

	// Validate input
	var input orm.MessageAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create message
	messageDB := orm.MessageDB{}
	messageDB.MessagePointersEnconding = input.MessagePointersEnconding
	messageDB.CopyBasicFieldsFromMessage(&input.Message)

	query := db.Create(&messageDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, messageDB)
}

// GetMessage
//
// swagger:route GET /messages/{ID} messages getMessage
//
// Gets the details for a message.
//
// Responses:
//    default: genericError
//        200: messageDBResponse
func GetMessage(c *gin.Context) {
	db := orm.BackRepo.BackRepoMessage.GetDB()

	// Get messageDB in DB
	var messageDB orm.MessageDB
	if err := db.First(&messageDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var messageAPI orm.MessageAPI
	messageAPI.ID = messageDB.ID
	messageAPI.MessagePointersEnconding = messageDB.MessagePointersEnconding
	messageDB.CopyBasicFieldsToMessage(&messageAPI.Message)

	c.JSON(http.StatusOK, messageAPI)
}

// UpdateMessage
//
// swagger:route PATCH /messages/{ID} messages updateMessage
//
// Update a message
//
// Responses:
//    default: genericError
//        200: messageDBResponse
func UpdateMessage(c *gin.Context) {
	db := orm.BackRepo.BackRepoMessage.GetDB()

	// Get model if exist
	var messageDB orm.MessageDB

	// fetch the message
	query := db.First(&messageDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.MessageAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	messageDB.CopyBasicFieldsFromMessage(&input.Message)
	messageDB.MessagePointersEnconding = input.MessagePointersEnconding

	query = db.Model(&messageDB).Updates(messageDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the messageDB
	c.JSON(http.StatusOK, messageDB)
}

// DeleteMessage
//
// swagger:route DELETE /messages/{ID} messages deleteMessage
//
// Delete a message
//
// Responses:
//    default: genericError
func DeleteMessage(c *gin.Context) {
	db := orm.BackRepo.BackRepoMessage.GetDB()

	// Get model if exist
	var messageDB orm.MessageDB
	if err := db.First(&messageDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&messageDB)

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
