// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gongfly/go/models"
	"github.com/fullstack-lang/gongfly/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __OpsLine__dummysDeclaration__ models.OpsLine
var __OpsLine_time__dummyDeclaration time.Duration

// An OpsLineID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getOpsLine updateOpsLine deleteOpsLine
type OpsLineID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// OpsLineInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postOpsLine updateOpsLine
type OpsLineInput struct {
	// The OpsLine to submit or modify
	// in: body
	OpsLine *orm.OpsLineAPI
}

// GetOpsLines
//
// swagger:route GET /opslines opslines getOpsLines
//
// # Get all opslines
//
// Responses:
// default: genericError
//
//	200: opslineDBResponse
func GetOpsLines(c *gin.Context) {
	db := orm.BackRepo.BackRepoOpsLine.GetDB()

	// source slice
	var opslineDBs []orm.OpsLineDB
	query := db.Find(&opslineDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	opslineAPIs := make([]orm.OpsLineAPI, 0)

	// for each opsline, update fields from the database nullable fields
	for idx := range opslineDBs {
		opslineDB := &opslineDBs[idx]
		_ = opslineDB
		var opslineAPI orm.OpsLineAPI

		// insertion point for updating fields
		opslineAPI.ID = opslineDB.ID
		opslineDB.CopyBasicFieldsToOpsLine(&opslineAPI.OpsLine)
		opslineAPI.OpsLinePointersEnconding = opslineDB.OpsLinePointersEnconding
		opslineAPIs = append(opslineAPIs, opslineAPI)
	}

	c.JSON(http.StatusOK, opslineAPIs)
}

// PostOpsLine
//
// swagger:route POST /opslines opslines postOpsLine
//
// Creates a opsline
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostOpsLine(c *gin.Context) {
	db := orm.BackRepo.BackRepoOpsLine.GetDB()

	// Validate input
	var input orm.OpsLineAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create opsline
	opslineDB := orm.OpsLineDB{}
	opslineDB.OpsLinePointersEnconding = input.OpsLinePointersEnconding
	opslineDB.CopyBasicFieldsFromOpsLine(&input.OpsLine)

	query := db.Create(&opslineDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoOpsLine.CheckoutPhaseOneInstance(&opslineDB)
	opsline := (*orm.BackRepo.BackRepoOpsLine.Map_OpsLineDBID_OpsLinePtr)[opslineDB.ID]

	if opsline != nil {
		models.AfterCreateFromFront(&models.Stage, opsline)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, opslineDB)
}

// GetOpsLine
//
// swagger:route GET /opslines/{ID} opslines getOpsLine
//
// Gets the details for a opsline.
//
// Responses:
// default: genericError
//
//	200: opslineDBResponse
func GetOpsLine(c *gin.Context) {
	db := orm.BackRepo.BackRepoOpsLine.GetDB()

	// Get opslineDB in DB
	var opslineDB orm.OpsLineDB
	if err := db.First(&opslineDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var opslineAPI orm.OpsLineAPI
	opslineAPI.ID = opslineDB.ID
	opslineAPI.OpsLinePointersEnconding = opslineDB.OpsLinePointersEnconding
	opslineDB.CopyBasicFieldsToOpsLine(&opslineAPI.OpsLine)

	c.JSON(http.StatusOK, opslineAPI)
}

// UpdateOpsLine
//
// swagger:route PATCH /opslines/{ID} opslines updateOpsLine
//
// # Update a opsline
//
// Responses:
// default: genericError
//
//	200: opslineDBResponse
func UpdateOpsLine(c *gin.Context) {
	db := orm.BackRepo.BackRepoOpsLine.GetDB()

	// Get model if exist
	var opslineDB orm.OpsLineDB

	// fetch the opsline
	query := db.First(&opslineDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.OpsLineAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	opslineDB.CopyBasicFieldsFromOpsLine(&input.OpsLine)
	opslineDB.OpsLinePointersEnconding = input.OpsLinePointersEnconding

	query = db.Model(&opslineDB).Updates(opslineDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	opslineNew := new(models.OpsLine)
	opslineDB.CopyBasicFieldsToOpsLine(opslineNew)

	// get stage instance from DB instance, and call callback function
	opslineOld := (*orm.BackRepo.BackRepoOpsLine.Map_OpsLineDBID_OpsLinePtr)[opslineDB.ID]
	if opslineOld != nil {
		models.AfterUpdateFromFront(&models.Stage, opslineOld, opslineNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the opslineDB
	c.JSON(http.StatusOK, opslineDB)
}

// DeleteOpsLine
//
// swagger:route DELETE /opslines/{ID} opslines deleteOpsLine
//
// # Delete a opsline
//
// default: genericError
//
//	200: opslineDBResponse
func DeleteOpsLine(c *gin.Context) {
	db := orm.BackRepo.BackRepoOpsLine.GetDB()

	// Get model if exist
	var opslineDB orm.OpsLineDB
	if err := db.First(&opslineDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&opslineDB)

	// get an instance (not staged) from DB instance, and call callback function
	opslineDeleted := new(models.OpsLine)
	opslineDB.CopyBasicFieldsToOpsLine(opslineDeleted)

	// get stage instance from DB instance, and call callback function
	opslineStaged := (*orm.BackRepo.BackRepoOpsLine.Map_OpsLineDBID_OpsLinePtr)[opslineDB.ID]
	if opslineStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, opslineStaged, opslineDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
