// generated by genORMTranslation.go
package orm

import (
	"bufio"
	"bytes"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"

	"gorm.io/gorm"

	"github.com/fullstack-lang/gongfly/go/models"

	"github.com/tealeg/xlsx/v3"
)

// BackRepoStruct supports callback functions
type BackRepoStruct struct {
	// insertion point for per struct back repo declarations
	BackRepoCivilianAirport BackRepoCivilianAirportStruct

	BackRepoLiner BackRepoLinerStruct

	BackRepoMessage BackRepoMessageStruct

	BackRepoOpsLine BackRepoOpsLineStruct

	BackRepoOrder BackRepoOrderStruct

	BackRepoRadar BackRepoRadarStruct

	BackRepoReport BackRepoReportStruct

	BackRepoScenario BackRepoScenarioStruct

	CommitNb uint // this ng is updated at the BackRepo level but also at the BackRepo<GongStruct> level

	PushFromFrontNb uint // records increments from push from front
}

func (backRepo *BackRepoStruct) GetLastCommitNb() uint {
	return backRepo.CommitNb
}

func (backRepo *BackRepoStruct) GetLastPushFromFrontNb() uint {
	return backRepo.PushFromFrontNb
}

func (backRepo *BackRepoStruct) IncrementCommitNb() uint {
	if models.Stage.OnInitCommitCallback != nil {
		models.Stage.OnInitCommitCallback.BeforeCommit(&models.Stage)
	}
	backRepo.CommitNb = backRepo.CommitNb + 1
	return backRepo.CommitNb
}

func (backRepo *BackRepoStruct) IncrementPushFromFrontNb() uint {
	backRepo.PushFromFrontNb = backRepo.PushFromFrontNb + 1
	return backRepo.CommitNb
}

// Init the BackRepoStruct inner variables and link to the database
func (backRepo *BackRepoStruct) init(db *gorm.DB) {
	// insertion point for per struct back repo declarations
	backRepo.BackRepoCivilianAirport.Init(db)
	backRepo.BackRepoLiner.Init(db)
	backRepo.BackRepoMessage.Init(db)
	backRepo.BackRepoOpsLine.Init(db)
	backRepo.BackRepoOrder.Init(db)
	backRepo.BackRepoRadar.Init(db)
	backRepo.BackRepoReport.Init(db)
	backRepo.BackRepoScenario.Init(db)

	models.Stage.BackRepo = backRepo
}

// Commit the BackRepoStruct inner variables and link to the database
func (backRepo *BackRepoStruct) Commit(stage *models.StageStruct) {
	// insertion point for per struct back repo phase one commit
	backRepo.BackRepoCivilianAirport.CommitPhaseOne(stage)
	backRepo.BackRepoLiner.CommitPhaseOne(stage)
	backRepo.BackRepoMessage.CommitPhaseOne(stage)
	backRepo.BackRepoOpsLine.CommitPhaseOne(stage)
	backRepo.BackRepoOrder.CommitPhaseOne(stage)
	backRepo.BackRepoRadar.CommitPhaseOne(stage)
	backRepo.BackRepoReport.CommitPhaseOne(stage)
	backRepo.BackRepoScenario.CommitPhaseOne(stage)

	// insertion point for per struct back repo phase two commit
	backRepo.BackRepoCivilianAirport.CommitPhaseTwo(backRepo)
	backRepo.BackRepoLiner.CommitPhaseTwo(backRepo)
	backRepo.BackRepoMessage.CommitPhaseTwo(backRepo)
	backRepo.BackRepoOpsLine.CommitPhaseTwo(backRepo)
	backRepo.BackRepoOrder.CommitPhaseTwo(backRepo)
	backRepo.BackRepoRadar.CommitPhaseTwo(backRepo)
	backRepo.BackRepoReport.CommitPhaseTwo(backRepo)
	backRepo.BackRepoScenario.CommitPhaseTwo(backRepo)

	backRepo.IncrementCommitNb()
}

// Checkout the database into the stage
func (backRepo *BackRepoStruct) Checkout(stage *models.StageStruct) {
	// insertion point for per struct back repo phase one commit
	backRepo.BackRepoCivilianAirport.CheckoutPhaseOne()
	backRepo.BackRepoLiner.CheckoutPhaseOne()
	backRepo.BackRepoMessage.CheckoutPhaseOne()
	backRepo.BackRepoOpsLine.CheckoutPhaseOne()
	backRepo.BackRepoOrder.CheckoutPhaseOne()
	backRepo.BackRepoRadar.CheckoutPhaseOne()
	backRepo.BackRepoReport.CheckoutPhaseOne()
	backRepo.BackRepoScenario.CheckoutPhaseOne()

	// insertion point for per struct back repo phase two commit
	backRepo.BackRepoCivilianAirport.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoLiner.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoMessage.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoOpsLine.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoOrder.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoRadar.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoReport.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoScenario.CheckoutPhaseTwo(backRepo)
}

var BackRepo BackRepoStruct

func GetLastCommitNb() uint {
	return BackRepo.GetLastCommitNb()
}

func GetLastPushFromFrontNb() uint {
	return BackRepo.GetLastPushFromFrontNb()
}

// Backup the BackRepoStruct
func (backRepo *BackRepoStruct) Backup(stage *models.StageStruct, dirPath string) {
	os.Mkdir(dirPath, os.ModePerm)

	// insertion point for per struct backup
	backRepo.BackRepoCivilianAirport.Backup(dirPath)
	backRepo.BackRepoLiner.Backup(dirPath)
	backRepo.BackRepoMessage.Backup(dirPath)
	backRepo.BackRepoOpsLine.Backup(dirPath)
	backRepo.BackRepoOrder.Backup(dirPath)
	backRepo.BackRepoRadar.Backup(dirPath)
	backRepo.BackRepoReport.Backup(dirPath)
	backRepo.BackRepoScenario.Backup(dirPath)
}

// Backup in XL the BackRepoStruct
func (backRepo *BackRepoStruct) BackupXL(stage *models.StageStruct, dirPath string) {
	os.Mkdir(dirPath, os.ModePerm)

	// open an existing file
	file := xlsx.NewFile()

	// insertion point for per struct backup
	backRepo.BackRepoCivilianAirport.BackupXL(file)
	backRepo.BackRepoLiner.BackupXL(file)
	backRepo.BackRepoMessage.BackupXL(file)
	backRepo.BackRepoOpsLine.BackupXL(file)
	backRepo.BackRepoOrder.BackupXL(file)
	backRepo.BackRepoRadar.BackupXL(file)
	backRepo.BackRepoReport.BackupXL(file)
	backRepo.BackRepoScenario.BackupXL(file)

	var b bytes.Buffer
	writer := bufio.NewWriter(&b)
	file.Write(writer)
	theBytes := b.Bytes()

	filename := filepath.Join(dirPath, "bckp.xlsx")
	err := ioutil.WriteFile(filename, theBytes, 0644)
	if err != nil {
		log.Panic("Cannot write the XL file", err.Error())
	}
}

// Restore the database into the back repo
func (backRepo *BackRepoStruct) Restore(stage *models.StageStruct, dirPath string) {
	models.Stage.Commit()
	models.Stage.Reset()
	models.Stage.Checkout()

	//
	// restauration first phase (create DB instance with new IDs)
	//

	// insertion point for per struct backup
	backRepo.BackRepoCivilianAirport.RestorePhaseOne(dirPath)
	backRepo.BackRepoLiner.RestorePhaseOne(dirPath)
	backRepo.BackRepoMessage.RestorePhaseOne(dirPath)
	backRepo.BackRepoOpsLine.RestorePhaseOne(dirPath)
	backRepo.BackRepoOrder.RestorePhaseOne(dirPath)
	backRepo.BackRepoRadar.RestorePhaseOne(dirPath)
	backRepo.BackRepoReport.RestorePhaseOne(dirPath)
	backRepo.BackRepoScenario.RestorePhaseOne(dirPath)

	//
	// restauration second phase (reindex pointers with the new ID)
	//

	// insertion point for per struct backup
	backRepo.BackRepoCivilianAirport.RestorePhaseTwo()
	backRepo.BackRepoLiner.RestorePhaseTwo()
	backRepo.BackRepoMessage.RestorePhaseTwo()
	backRepo.BackRepoOpsLine.RestorePhaseTwo()
	backRepo.BackRepoOrder.RestorePhaseTwo()
	backRepo.BackRepoRadar.RestorePhaseTwo()
	backRepo.BackRepoReport.RestorePhaseTwo()
	backRepo.BackRepoScenario.RestorePhaseTwo()

	models.Stage.Checkout()
}

// Restore the database into the back repo
func (backRepo *BackRepoStruct) RestoreXL(stage *models.StageStruct, dirPath string) {
}
