// generated by genORMTranslation.go
package orm

import (
	"bufio"
	"bytes"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"

	"gorm.io/gorm"

	"github.com/fullstack-lang/gongfly/go/models"

	"github.com/tealeg/xlsx/v3"
)

// BackRepoStruct supports callback functions
type BackRepoStruct struct {
	// insertion point for per struct back repo declarations
	BackRepoCivilianAirport BackRepoCivilianAirportStruct

	BackRepoLiner BackRepoLinerStruct

	BackRepoMessage BackRepoMessageStruct

	BackRepoOpsLine BackRepoOpsLineStruct

	BackRepoRadar BackRepoRadarStruct

	BackRepoSatellite BackRepoSatelliteStruct

	BackRepoScenario BackRepoScenarioStruct

	CommitFromBackNb uint // this ng is updated at the BackRepo level but also at the BackRepo<GongStruct> level

	PushFromFrontNb uint // records increments from push from front

	stage *models.StageStruct
}

func (backRepo *BackRepoStruct) GetStage() (stage *models.StageStruct) {
	stage = backRepo.stage
	return
}

func (backRepo *BackRepoStruct) GetLastCommitFromBackNb() uint {
	return backRepo.CommitFromBackNb
}

func (backRepo *BackRepoStruct) GetLastPushFromFrontNb() uint {
	return backRepo.PushFromFrontNb
}

func (backRepo *BackRepoStruct) IncrementCommitFromBackNb() uint {
	if backRepo.stage.OnInitCommitCallback != nil {
		backRepo.stage.OnInitCommitCallback.BeforeCommit(backRepo.stage)
	}
	if backRepo.stage.OnInitCommitFromBackCallback != nil {
		backRepo.stage.OnInitCommitFromBackCallback.BeforeCommit(backRepo.stage)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
	return backRepo.CommitFromBackNb
}

func (backRepo *BackRepoStruct) IncrementPushFromFrontNb() uint {
	if backRepo.stage.OnInitCommitCallback != nil {
		backRepo.stage.OnInitCommitCallback.BeforeCommit(backRepo.stage)
	}
	if backRepo.stage.OnInitCommitFromFrontCallback != nil {
		backRepo.stage.OnInitCommitFromFrontCallback.BeforeCommit(backRepo.stage)
	}
	backRepo.PushFromFrontNb = backRepo.PushFromFrontNb + 1
	return backRepo.CommitFromBackNb
}

// Init the BackRepoStruct inner variables and link to the database
func (backRepo *BackRepoStruct) init(stage *models.StageStruct, db *gorm.DB) {
	// insertion point for per struct back repo declarations
	backRepo.BackRepoCivilianAirport.Init(stage, db)
	backRepo.BackRepoLiner.Init(stage, db)
	backRepo.BackRepoMessage.Init(stage, db)
	backRepo.BackRepoOpsLine.Init(stage, db)
	backRepo.BackRepoRadar.Init(stage, db)
	backRepo.BackRepoSatellite.Init(stage, db)
	backRepo.BackRepoScenario.Init(stage, db)

	stage.BackRepo = backRepo
	backRepo.stage = stage
}

// Commit the BackRepoStruct inner variables and link to the database
func (backRepo *BackRepoStruct) Commit(stage *models.StageStruct) {
	// insertion point for per struct back repo phase one commit
	backRepo.BackRepoCivilianAirport.CommitPhaseOne(stage)
	backRepo.BackRepoLiner.CommitPhaseOne(stage)
	backRepo.BackRepoMessage.CommitPhaseOne(stage)
	backRepo.BackRepoOpsLine.CommitPhaseOne(stage)
	backRepo.BackRepoRadar.CommitPhaseOne(stage)
	backRepo.BackRepoSatellite.CommitPhaseOne(stage)
	backRepo.BackRepoScenario.CommitPhaseOne(stage)

	// insertion point for per struct back repo phase two commit
	backRepo.BackRepoCivilianAirport.CommitPhaseTwo(backRepo)
	backRepo.BackRepoLiner.CommitPhaseTwo(backRepo)
	backRepo.BackRepoMessage.CommitPhaseTwo(backRepo)
	backRepo.BackRepoOpsLine.CommitPhaseTwo(backRepo)
	backRepo.BackRepoRadar.CommitPhaseTwo(backRepo)
	backRepo.BackRepoSatellite.CommitPhaseTwo(backRepo)
	backRepo.BackRepoScenario.CommitPhaseTwo(backRepo)

	backRepo.IncrementCommitFromBackNb()
}

// Checkout the database into the stage
func (backRepo *BackRepoStruct) Checkout(stage *models.StageStruct) {
	// insertion point for per struct back repo phase one commit
	backRepo.BackRepoCivilianAirport.CheckoutPhaseOne()
	backRepo.BackRepoLiner.CheckoutPhaseOne()
	backRepo.BackRepoMessage.CheckoutPhaseOne()
	backRepo.BackRepoOpsLine.CheckoutPhaseOne()
	backRepo.BackRepoRadar.CheckoutPhaseOne()
	backRepo.BackRepoSatellite.CheckoutPhaseOne()
	backRepo.BackRepoScenario.CheckoutPhaseOne()

	// insertion point for per struct back repo phase two commit
	backRepo.BackRepoCivilianAirport.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoLiner.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoMessage.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoOpsLine.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoRadar.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoSatellite.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoScenario.CheckoutPhaseTwo(backRepo)
}

var BackRepo BackRepoStruct

func GetLastCommitFromBackNb() uint {
	return BackRepo.GetLastCommitFromBackNb()
}

func GetLastPushFromFrontNb() uint {
	return BackRepo.GetLastPushFromFrontNb()
}

// Backup the BackRepoStruct
func (backRepo *BackRepoStruct) Backup(stage *models.StageStruct, dirPath string) {
	os.MkdirAll(dirPath, os.ModePerm)

	// insertion point for per struct backup
	backRepo.BackRepoCivilianAirport.Backup(dirPath)
	backRepo.BackRepoLiner.Backup(dirPath)
	backRepo.BackRepoMessage.Backup(dirPath)
	backRepo.BackRepoOpsLine.Backup(dirPath)
	backRepo.BackRepoRadar.Backup(dirPath)
	backRepo.BackRepoSatellite.Backup(dirPath)
	backRepo.BackRepoScenario.Backup(dirPath)
}

// Backup in XL the BackRepoStruct
func (backRepo *BackRepoStruct) BackupXL(stage *models.StageStruct, dirPath string) {
	os.MkdirAll(dirPath, os.ModePerm)

	// open an existing file
	file := xlsx.NewFile()

	// insertion point for per struct backup
	backRepo.BackRepoCivilianAirport.BackupXL(file)
	backRepo.BackRepoLiner.BackupXL(file)
	backRepo.BackRepoMessage.BackupXL(file)
	backRepo.BackRepoOpsLine.BackupXL(file)
	backRepo.BackRepoRadar.BackupXL(file)
	backRepo.BackRepoSatellite.BackupXL(file)
	backRepo.BackRepoScenario.BackupXL(file)

	var b bytes.Buffer
	writer := bufio.NewWriter(&b)
	file.Write(writer)
	theBytes := b.Bytes()

	filename := filepath.Join(dirPath, "bckp.xlsx")
	err := ioutil.WriteFile(filename, theBytes, 0644)
	if err != nil {
		log.Panic("Cannot write the XL file", err.Error())
	}
}

// Restore the database into the back repo
func (backRepo *BackRepoStruct) Restore(stage *models.StageStruct, dirPath string) {
	backRepo.stage.Commit()
	backRepo.stage.Reset()
	backRepo.stage.Checkout()

	//
	// restauration first phase (create DB instance with new IDs)
	//

	// insertion point for per struct backup
	backRepo.BackRepoCivilianAirport.RestorePhaseOne(dirPath)
	backRepo.BackRepoLiner.RestorePhaseOne(dirPath)
	backRepo.BackRepoMessage.RestorePhaseOne(dirPath)
	backRepo.BackRepoOpsLine.RestorePhaseOne(dirPath)
	backRepo.BackRepoRadar.RestorePhaseOne(dirPath)
	backRepo.BackRepoSatellite.RestorePhaseOne(dirPath)
	backRepo.BackRepoScenario.RestorePhaseOne(dirPath)

	//
	// restauration second phase (reindex pointers with the new ID)
	//

	// insertion point for per struct backup
	backRepo.BackRepoCivilianAirport.RestorePhaseTwo()
	backRepo.BackRepoLiner.RestorePhaseTwo()
	backRepo.BackRepoMessage.RestorePhaseTwo()
	backRepo.BackRepoOpsLine.RestorePhaseTwo()
	backRepo.BackRepoRadar.RestorePhaseTwo()
	backRepo.BackRepoSatellite.RestorePhaseTwo()
	backRepo.BackRepoScenario.RestorePhaseTwo()

	backRepo.stage.Checkout()
}

// Restore the database into the back repo
func (backRepo *BackRepoStruct) RestoreXL(stage *models.StageStruct, dirPath string) {

	// clean the stage
	backRepo.stage.Reset()

	// commit the cleaned stage
	backRepo.stage.Commit()

	// open an existing file
	filename := filepath.Join(dirPath, "bckp.xlsx")
	file, err := xlsx.OpenFile(filename)
	_ = file

	if err != nil {
		log.Panic("Cannot read the XL file", err.Error())
	}

	//
	// restauration first phase (create DB instance with new IDs)
	//

	// insertion point for per struct backup
	backRepo.BackRepoCivilianAirport.RestoreXLPhaseOne(file)
	backRepo.BackRepoLiner.RestoreXLPhaseOne(file)
	backRepo.BackRepoMessage.RestoreXLPhaseOne(file)
	backRepo.BackRepoOpsLine.RestoreXLPhaseOne(file)
	backRepo.BackRepoRadar.RestoreXLPhaseOne(file)
	backRepo.BackRepoSatellite.RestoreXLPhaseOne(file)
	backRepo.BackRepoScenario.RestoreXLPhaseOne(file)

	// commit the restored stage
	backRepo.stage.Commit()
}
