// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { MessageDB } from '../message-db'
import { MessageService } from '../message.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-message-sorting',
  templateUrl: './message-sorting.component.html',
  styleUrls: ['./message-sorting.component.css']
})
export class MessageSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Message instances that are in the association
  associatedMessages = new Array<MessageDB>();

  constructor(
    private messageService: MessageService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of message instances
    public dialogRef: MatDialogRef<MessageSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getMessages()
  }

  getMessages(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let message of this.frontRepo.Messages_array) {
          let ID = this.dialogData.ID
          let revPointerID = message[this.dialogData.ReversePointer as keyof MessageDB] as unknown as NullInt64
          let revPointerID_Index = message[this.dialogData.ReversePointer + "_Index" as keyof MessageDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedMessages.push(message)
          }
        }

        // sort associated message according to order
        this.associatedMessages.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedMessages, event.previousIndex, event.currentIndex);

    // set the order of Message instances
    let index = 0

    for (let message of this.associatedMessages) {
      let revPointerID_Index = message[this.dialogData.ReversePointer + "_Index" as keyof MessageDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedMessages.forEach(
      message => {
        this.messageService.updateMessage(message, this.dialogData.GONG__StackPath)
          .subscribe(message => {
            this.messageService.MessageServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
